# Generated by Django 5.0.6 on 2024-06-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_remove_buyer_need_item_volume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer_need',
            name='item_shape',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
