# Generated by Django 5.0.6 on 2024-06-07 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_buyer_need_item_shape'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer_need',
            name='item_name',
        ),
    ]
