# Generated by Django 5.0.6 on 2024-06-07 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(max_length=50, unique=True)),
                ('seller_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='seller_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=50)),
                ('item_material_type', models.CharField(max_length=100)),
                ('item_grade', models.CharField(max_length=50)),
                ('item_condition', models.CharField(blank=True, max_length=400, null=True)),
                ('item_weight', models.FloatField(blank=True, null=True)),
                ('item_picture', models.ImageField(blank=True, null=True, upload_to='seller_card_pictures')),
                ('seller', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='seller.seller')),
            ],
        ),
    ]
