# Generated by Django 5.0.6 on 2024-06-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_product',
            name='item_condition',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='seller_product',
            name='item_cost',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='seller_product',
            name='item_volume',
            field=models.BooleanField(null=True),
        ),
    ]
