# Generated by Django 5.0.6 on 2024-06-08 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller_product',
            name='item_picture',
        ),
    ]
