# Generated by Django 5.0.6 on 2024-06-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_remove_seller_product_item_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_product',
            name='item_picture',
            field=models.ImageField(blank=True, null=True, upload_to='seller_card_pictures'),
        ),
    ]
