# Generated by Django 5.0.6 on 2024-06-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_seller_product_item_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_product',
            name='item_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='seller_product',
            name='item_volume',
            field=models.FloatField(null=True),
        ),
    ]
