# Generated by Django 5.0.6 on 2024-06-03 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_alter_seller_product_item_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='seller_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(max_length=50)),
                ('seller_name', models.CharField(max_length=200)),
                ('item_condition', models.CharField(max_length=400, null=True)),
                ('item_cost', models.FloatField(null=True)),
                ('item_picture', models.ImageField(null=True, upload_to='seller_card_pictures')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller_product')),
            ],
        ),
    ]
