# Generated by Django 5.0.6 on 2024-06-08 13:15

import seller.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_seller_product_item_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_product',
            name='item_picture',
            field=models.ImageField(blank=True, null=True, upload_to=seller.models.upload_to, verbose_name='Image'),
        ),
    ]
