# Generated by Django 5.0.6 on 2024-06-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_seller_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_card',
            name='item_condition',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='seller_card',
            name='item_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seller_card',
            name='item_picture',
            field=models.ImageField(blank=True, null=True, upload_to='seller_card_pictures'),
        ),
        migrations.AlterField(
            model_name='seller_product',
            name='item_condition',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='seller_product',
            name='item_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seller_product',
            name='item_volume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
