# Generated by Django 5.0.6 on 2024-06-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_alter_seller_card_item_condition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(max_length=50, unique=True)),
                ('seller_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='seller_card',
            name='seller_id',
        ),
        migrations.RemoveField(
            model_name='seller_card',
            name='seller_name',
        ),
    ]
