# Generated by Django 5.0.6 on 2024-06-03 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_seller_remove_seller_card_seller_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_product',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='seller.seller'),
        ),
    ]
