# Generated by Django 5.0.6 on 2024-06-08 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_alter_seller_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='seller_id',
        ),
    ]



