# Generated by Django 5.0.6 on 2024-06-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_seller_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller_product',
            name='item_volume',
        ),
        migrations.AddField(
            model_name='seller_product',
            name='item_picture',
            field=models.ImageField(blank=True, null=True, upload_to='seller_card_pictures'),
        ),
        migrations.AddField(
            model_name='seller_product',
            name='item_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
