# Generated by Django 5.0.6 on 2024-06-04 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_remove_seller_product_item_volume_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='seller_card',
        ),
    ]
