# Generated by Django 5.0.6 on 2024-06-08 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0009_alter_seller_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_product',
            name='seller',
            field=models.ForeignKey(default='4', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='seller.seller'),
            preserve_default=False,
        ),
    ]
