# Generated by Django 5.0.6 on 2024-06-07 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0009_delete_seller_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller_product',
            name='item_cost',
        ),
        migrations.RemoveField(
            model_name='seller_product',
            name='item_name',
        ),
    ]
