# Generated by Django 5.0.6 on 2024-06-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0010_alter_seller_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='seller_contact',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
