# Generated by Django 5.0.6 on 2024-06-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0012_alter_seller_seller_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='seller_email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
