# Generated by Django 5.0.6 on 2024-06-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0014_rename_seller_name_seller_seller_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='seller_company_name',
            field=models.CharField(default='company', max_length=200),
            preserve_default=False,
        ),
    ]
